import {
  Controller,
  Get,
  Post,
  Patch,
  Delete,
  Body,
  Param,
  Query,
  UseGuards,
} from '@nestjs/common';
import { ApiTags, ApiBearerAuth, ApiOperation } from '@nestjs/swagger';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { RolesGuard } from '../../common/guards/roles.guard';
import { Roles } from '../../common/decorators/roles.decorator';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import { PaginationDto } from '../../common/dto/pagination.dto';
import { ApiResponse } from '../../common/dto/api-response.dto';
import { SchedulesService } from './schedules.service';
import { AutoSchedulerService } from './services/auto-scheduler.service';
import { ConflictDetectionService } from './services/conflict-detection.service';
import { CreateScheduleDto } from './dto/create-schedule.dto';
import { UpdateScheduleDto } from './dto/update-schedule.dto';
import { AutoGenerateDto } from './dto/auto-generate.dto';
import { CheckConflictDto } from './dto/check-conflict.dto';

@ApiTags('Schedules')
@ApiBearerAuth()
@UseGuards(JwtAuthGuard, RolesGuard)
@Controller('schedules')
export class SchedulesController {
  constructor(
    private readonly schedulesService: SchedulesService,
    private readonly autoScheduler: AutoSchedulerService,
    private readonly conflictService: ConflictDetectionService,
  ) {}

  @Get()
  @ApiOperation({ summary: 'List schedules' })
  async findAll(
    @Query() pagination: PaginationDto,
    @Query('semester') semester?: string,
    @Query('teacherId') teacherId?: string,
    @Query('classId') classId?: string,
    @Query('roomId') roomId?: string,
    @CurrentUser() user?: any,
  ) {
    let effectiveTeacherId = teacherId;

    // Non-admin users can only view schedules for their own teacher record
    // Admin can view any teacher's schedule by passing teacherId filter
    if (user?.role === 'teacher' && !teacherId) {
      effectiveTeacherId = user.teacherId;
    }

    const result = await this.schedulesService.findAll(pagination, {
      semester,
      teacherId: effectiveTeacherId,
      classId,
      roomId,
    });
    return ApiResponse.success(result);
  }

  @Post()
  @Roles('admin')
  @ApiOperation({ summary: 'Create schedule' })
  async create(@Body() dto: CreateScheduleDto, @CurrentUser('id') userId: string) {
    const result = await this.schedulesService.create(dto, userId);
    return ApiResponse.success(result, 'Schedule created');
  }

  @Get(':id')
  @ApiOperation({ summary: 'Get schedule detail' })
  async findOne(@Param('id') id: string) {
    const result = await this.schedulesService.findOne(id);
    return ApiResponse.success(result);
  }

  @Patch(':id')
  @Roles('admin')
  @ApiOperation({ summary: 'Update schedule (with optimistic locking)' })
  async update(
    @Param('id') id: string,
    @Body() dto: UpdateScheduleDto,
    @CurrentUser('id') userId: string,
  ) {
    const result = await this.schedulesService.update(id, dto, userId);
    return ApiResponse.success(result, 'Schedule updated');
  }

  @Delete(':id')
  @Roles('admin')
  @ApiOperation({ summary: 'Cancel schedule' })
  async remove(@Param('id') id: string, @CurrentUser('id') userId: string) {
    await this.schedulesService.remove(id, userId);
    return ApiResponse.success(null, 'Schedule cancelled');
  }

  @Post('auto-generate')
  @Roles('admin')
  @ApiOperation({ summary: 'Auto-generate schedules for a semester' })
  async autoGenerate(@Body() dto: AutoGenerateDto, @CurrentUser('id') userId: string) {
    const result = await this.autoScheduler.generate(dto.semester, dto.coursePlanIds, userId);
    return ApiResponse.success(result);
  }

  @Post('check-conflicts')
  @ApiOperation({ summary: 'Check scheduling conflicts' })
  async checkConflicts(@Body() dto: CheckConflictDto) {
    const conflicts = await this.conflictService.checkConflicts({
      roomId: dto.roomId,
      teacherId: dto.teacherId,
      classId: dto.classId,
      dayOfWeek: dto.dayOfWeek,
      period: dto.period,
      weekStart: dto.weekStart,
      weekEnd: dto.weekEnd,
      excludeScheduleId: dto.excludeScheduleId,
    });
    return ApiResponse.success(conflicts);
  }

  @Get(':id/history')
  @ApiOperation({ summary: 'Get schedule change history' })
  async getHistory(@Param('id') id: string) {
    const history = await this.schedulesService.getHistory(id);
    return ApiResponse.success(history);
  }
}
