import { IsString, IsNotEmpty, IsOptional, IsArray, IsUUID } from 'class-validator';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';

export class AutoGenerateDto {
  @ApiProperty({ example: '2025-2026-1' })
  @IsString()
  @IsNotEmpty()
  semester: string;

  @ApiPropertyOptional()
  @IsOptional()
  @IsArray()
  @IsUUID('4', { each: true })
  coursePlanIds?: string[];
}
